apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: app-build-test-push
spec:
  params:
    - name: url
      type: string
      description: url of the git repository to clone
    - name: dockerfile
      type: string
      description: Path to the dockerfile within the project cloned
    - name: output-image
      type: string
      description: Fully Qualified Output Image
    - description: A boolean indicating whether we would like to perform a quarkus native build
      default: "false"
      name: native
      type: string
    - description: A boolean indicating whether we would like to execute a task
      default: "false"
      name: debug
      type: string
    - description: boolean which allows to deploy the application on the cluster with the generated resources
      default: "true"
      name: deploy
      type: string
  workspaces:
    - name: project-dir
    - name: maven-m2-repo
    - name: maven-settings
    - name: dockerconfig-ws
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
      workspaces:
        - name: project-dir
          workspace: project-dir

    - name: maven-package
      taskRef:
        name: maven
      params:
        - name: GOALS
          value:
            - package
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: project-dir
          workspace: project-dir
        - name: maven-m2-repo
          workspace: maven-m2-repo

    - # This step is optional and only executed if native build is specified
      name: quarkus-native-build
      runAfter:
        - maven-package-test
      when:
        - input: $(params.native)
          operator: in
          values: [ "true" ]
      taskRef:
        name: quarkus-native-build
      workspaces:
        - name: project-dir
          workspace: project-dir

    - name: buildah-image
      runAfter:
        - quarkus-native-build
        - maven-package-test
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: REGISTRY_AUTH_PATH
          value: $(workspaces.dockerconfig.path)
      workspaces:
        - name: source
          workspace: project-dir
        - name: dockerconfig
          workspace: dockerconfig-ws
