apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-test-push
spec:
  params:
    - name: url
      type: string
      description: url of the git repository to clone
    - name: dockerfile
      type: string
      description: Path to the dockerfile within the project cloned
      default: "src/main/docker/Dockerfile.jvm"
    - name: output-image
      type: string
      description: Fully Qualified Output Image
    - description: A boolean indicating whether we would like to perform a quarkus native build
      default: "false"
      name: native
      type: string
    - description: A boolean indicating whether we would like to execute a task
      default: "false"
      name: debug
      type: string
    - description: boolean which allows to deploy the application on the cluster with the generated resources
      default: "true"
      name: deploy
      type: string
    - description: Maven goals
      name: mavenGoals
      type: array
    - default: "true"
      description: boolean allowing to verify the TLS certificate during task execution like git clone, image push to a registry, etc
      name: sslVerify
      type: string
  workspaces:
    - name: project-dir
    - name: maven-repo-dir
    - name: maven-settings
    - name: dockerconfig-secret
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: sslVerify
          value: $(params.sslVerify)
      workspaces:
        - name: project-dir
          workspace: project-dir

    - name: maven-package-test
      taskRef:
        name: maven
      params:
        - name: DOCKER_CONFIG
          value: $(workspaces.dockerconfig.path)/config.json
        - name: GOALS
          value: [ "$(params.mavenGoals[*])" ]
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: project-dir
          workspace: project-dir
        - name: maven-local-repo # Wrong wks task's name. Rename then maven-repo-dir to maven-local-repo
          workspace: maven-repo-dir
        # NOT NEEDED AS DECLARED PASSED USING PARAM: REGISTRY_AUTH_PATH
        #- name: dockerconfig
        #  workspace: dockerconfig-secret

    - name: buildah-image
      runAfter:
        - maven-package-test
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: TLSVERIFY
          value: $(params.sslVerify)
        # THIS IS MANDATORY TO PASS THE CREDS FILE TO THE TASK FROM THE WKS
        - name: REGISTRY_AUTH_PATH
          value: $(workspaces.dockerconfig-secret.path)

      workspaces:
        - name: project-dir
          workspace: project-dir
        - name: dockerconfig-secret
          workspace: dockerconfig-secret

